import Head from "next/head";
import { Jost } from "next/font/google";
import styles from "../styles/Dashboard.module.css";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTwitter } from "@fortawesome/free-brands-svg-icons";
import { faLinkedin } from "@fortawesome/free-brands-svg-icons";
import { faGithub } from "@fortawesome/free-brands-svg-icons";
import Link from "next/link";

const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Container */}
      <div className={`${jost.variable} ${styles.centeredContainer}`}>
        <div className={styles.innerContent}>
          {/* Header */}
          <Image
            src="/images/icon.png"
            alt="Hero Image"
            width={55}
            height={70}
            className={styles.headerIcon}
          />
          <div>
            <h1 className={styles.headerTitle}>
              Let <i>AI</i> Review Your Resume Before <i>Recruiters</i> Do
            </h1>
            <div>
              {/* <Image
                src="/images/header.png"
                alt="Hero Image"
                width={1000}
                height={1000}
                className={styles.headerImage}
              /> */}
            </div>
          </div>

          {/* Features */}
          <div>
            {/* Title */}
            <div>
              <h2 className={styles.featuresTitle}>
                Exclusive <i>Features</i> for Job Seekers <br />
                Who Want to <i>Stand Out</i>
              </h2>
            </div>

            {/* Features List */}
            <div className={styles.featureList}>
              <div className={styles.featureItem}>
                <Image
                  src="/images/6.png"
                  width={294}
                  height={442}
                  className={styles.featureImage}
                  alt="Resume Breakdown"
                />
                <div className={styles.featureText}>
                  <h3>Resume Breakdown & Review</h3>
                  <p>
                    Get a detailed, section-by-section analysis that highlights
                    your strengths and shows where improvements can make the
                    most impact.
                  </p>
                </div>
              </div>

              <div className={styles.featureItem}>
                <Image
                  src="/images/7.png"
                  width={399}
                  height={439}
                  className={styles.featureImage}
                  alt="Skill Evaluation"
                />
                <div className={styles.featureText}>
                  <h3>Skill Evaluation</h3>
                  <p>
                    Pinpoints both your technical and soft skills—calling out
                    what's solid and what might be missing for the roles you
                    want.
                  </p>
                </div>
              </div>

              <div className={styles.featureItem}>
                <Image
                  src="/images/8.png"
                  width={365}
                  height={437}
                  className={styles.featureImage}
                  alt="Experience Insights"
                />
                <div className={styles.featureText}>
                  <h3>Experience Insights</h3>
                  <p>
                    Reviews your past roles and projects with a focus on
                    outcomes. We look for impact, metrics, and clarity.
                  </p>
                </div>
              </div>

              <div className={styles.featureItem}>
                <Image
                  src="/images/9.png"
                  width={402}
                  height={439}
                  className={styles.featureImage}
                  alt="Tone & Writing Style"
                />
                <div className={styles.featureText}>
                  <h3>Tone & Writing Style Check</h3>
                  <p>
                    Make sure your resume sounds confident, clear, and
                    professional. We catch vague phrases, passive language, and
                    inconsistent tone.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Call to Action */}
          <div className={styles.ctaSection}>
            {/* Left */}
            <div className={styles.ctaText}>
              <h2>
                Be the <span className={styles.emphasis}>first</span> to turn
                your resume into a competitive advantage.
              </h2>
              <p>
                With structured feedback, detailed skill insights, and clarity
                on how your experience reads to employers, you'll know exactly
                what to fix and how to present yourself with confidence. Whether
                you're applying for your first job or your next big career move,
                this is your edge in a crowded job market.
              </p>
              <Link href="/resume">
                <button className={styles.ctaButton}>Try It Out</button>
              </Link>
            </div>
            {/* Right */}
            <div className={styles.ctaImage}>
              <Image
                src="/images/10.png"
                width={400}
                height={400}
                alt="Resume advantage illustration"
              />
            </div>
          </div>

          {/* Footer */}
          <div className={styles.footer}>
            {/* Line */}
            <div className={styles.footerLine}></div>

            {/* Items */}
            <div className={styles.footerContent}>
              {/* Start - Name */}
              <div className={styles.footerName}>Georgette Dalen</div>

              {/* End - Social Links */}
              <div className={styles.footerLinks}>
                <a
                  href="https://x.com/ggoldffish"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <FontAwesomeIcon icon={faTwitter} />
                </a>
                <a
                  href="https://www.linkedin.com/in/georgettedalen"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <FontAwesomeIcon icon={faLinkedin} />
                </a>
                <a
                  href="https://github.com/grgttdln"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <FontAwesomeIcon icon={faGithub} />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
